version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nodeapp:
    image: stacklifo/backend-image:latest
    container_name: nodeapp
    ports:
      - "8000:8000"
    environment:
      DATAASE_URL: mongodb://mongodb:27017/blogify
    depends_on:
      - mongodb

volumes:
  mongodb_data: